[project]
name = "SS_2025_SWE"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Olivia", email = "ko8973@mci4me.at"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
